name: Create Repo on Issue

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:

    - name: List organization repositories
      env:
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: |
        gh repo list <org-name> --json name,visibility --jq '.[] | "\(.name): \(.visibility)"'

    
    - name: Create repo
      env:
        ORG_NAME: 'Epi-Stg-Hub'
        TEMPLATE_NAME: 'Template-Project'
        NEW_REPO_NAME: ${{ github.event.issue.title }}
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: |
        # Sanitize the issue name
        REPO_NAME=$(echo "$NEW_REPO_NAME" | tr ' ' '-')
        # create repo
        gh repo create $ORG_NAME/$REPO_NAME --internal -p $ORG_NAME/$TEMPLATE_NAME --include-all-branches
