name: Create Repo on Issue

on:
  issues:
    types: [labeled]

jobs:
  create-repo:
    if: ${{ github.event.label.name == 'Ongoing' }}
    runs-on: ubuntu-latest
    env:
        TEMPLATE_NAME: 'Template-Project'
        ORG_NAME: 'Epi-Stg-Hub'
        REPO_NAME: 'Config'
        ADMIN_NAME: '@Kaiwinta'
        NEW_REPO_NAME: ${{ github.event.issue.title }}
        ISSUE_NB: ${{ github.event.issue.number }}
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        ASSIGNEE: ${{ github.event.issue.assignees}}
      

    steps:
      - name: Create repo
        id: createRepo
        continue-on-error: true
        run: |
          # Sanitize the issue name
          REPO_NAME=$(echo "$NEW_REPO_NAME" | tr ' ' '-')
          # create repo
          gh repo create $ORG_NAME/$REPO_NAME --private -p $ORG_NAME/$TEMPLATE_NAME --include-all-branches

      - name: Comment on failure
        id: commentOnFailure
        if: steps.createRepo.outcome == 'failure'
        run: |
          gh issue comment $ISSUE_NB  --repo "$ORG_NAME/$REPO_NAME" -b "An error occured during the creation of the repo\\n\\nAdmin attention required $ADMIN_NAME"

  

    # - name: Create repo with template
    #   env:
    #     ORG_NAME: 'Epi-Stg-Hub'
    #     TEMPLATE_NAME: 'Template-Project'
    #     NEW_REPO_NAME: ${{ github.event.issue.title }}
    #     GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
    #   run: |
    #     # Sanitize the issue name
    #     REPO_NAME=$(echo "$NEW_REPO_NAME" | tr ' ' '-')
    #     # create repo
    #     gh repo create $ORG_NAME/$REPO_NAME --internal -p $ORG_NAME/$TEMPLATE_NAME --include-all-branches
      
  update-repo:
     if: ${{ github.event.label.name == 'Ongoing' }}
     runs-on: ubuntu-latest
     env:
       ORG_NAME: 'Epi-Stg-Hub'
       GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
       NEW_REPO_NAME: ${{ github.event.issue.title }}
       ASSIGNEE: ${{ github.event.issue.assignees}}

     steps:
     - name: Create Team
       run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        /orgs/my-org/teams \
        -f name="$NEW_REPO_NAME-team" \
        -f description="Team created for $NEW_REPO_NAME"
  
     - name: Assign People To team
       run: |
        for user in $ASSIGNEE; do
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          /orgs/my-org/teams/$NEW_REPO_NAME-team/memberships/$user
        done