name: Create Repo on Issue

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:

    - name: Auth gh CLI
      env:
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: |
        # Authenticate gh CLI
        echo "$GH_TOKEN" | gh auth login --with-token
        echo "gh CLI authenticated successfully."

    - name: Create repo
      env:
        ORG_NAME: 'Epi-Stg-Hub'
        TEMPLATE_NAME: 'Template-Project'
        NEW_REPO_NAME: ${{ github.event.issue.title }}
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: |
        # Sanitize the issue name
        REPO_NAME=$(echo "$NEW_REPO_NAME" | tr ' ' '-')
        # create repo
        gh repo create $ORG_NAME/$REPO_NAME --internal -p $ORG_NAME/$TEMPLATE_NAME --include-all-branches
