name: Create Repo on Issue

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v2
      with:
        token: ${{ secrets.ORG_ADMIN_TOKEN }}

    - name: Create repo
      env:
        ORG_NAME: 'Epi-Stg-Hub'
        NEW_REPO_NAME: ${{ github.event.issue.title }}
      run: |
        gh repo create $ORG_NAME/$NEW_REPO_NAME --public
