name: Create Repo on Issue

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:

    - name: Create repo
      env:
        ORG_NAME: 'Epi-Stg-Hub'
        TEMPLATE_NAME: 'Template-Project'
        NEW_REPO_NAME: ${{ github.event.issue.title }}
        GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
      run: |
        REPO_NAME=$(echo "$NEW_REPO_NAME" | tr ' ' '-')
        gh repo create $ORG_NAME/$NEW_REPO_NAME --internal -p $ORG_NAME/$TEMPLATE_NAME --include_all_branches
