name : merging

on:
    push:
        branches: ["main", "dev"]
    pull_request:
        branches:
            - dev

permissions:
    checks: write
    contents: write
    pull-requests: write

jobs:
    check_build:
        name: Valide-code
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 9.0.x
            - name: Compile project
              run: dotnet build --no-restore .\ConsoleApp1\ConsoleApp1